[main]
# Set your preferred font and size
font=FiraCode Nerd Font Mono:size=12
# Change your default shell
shell=/bin/zsh
# Initial window dimensions
initial-window-size-chars=100x30
# Pad terminal edges (in pixels)
pad=10x10

