#!/bin/bash

# You can call this script like this:
# $./brightness.sh up
# $./brightness.sh down

function get_brightness {
    sudo light | cut -d\. -f1
}

function send_notification {
    brightness=`get_brightness`
    # Make the bar with the special character ─ (it's not dash -)
    # https://en.wikipedia.org/wiki/Box-drawing_character
    bar=$(seq -s "─" $(($brightness / 5)) | sed 's/[0-9]//g')
    # Send the notification
    notify-send -i display-brightness-symbolic -t 8 -u normal "    $bar"
}

case $1 in
    up)
	# Set the brightness on
    sudo light -A 10
#	send_notification
	;;
    down)
    sudo light -U 10
#	send_notification
	;;
esac
