#!/usr/bin/bash
/usr/bin/setxkbmap -option "ctrl:nocaps"
#~/.screenlayout/def.sh
picom --config ~/.config/i3/picom.conf &
xbanish -i shift -i ctrl -i mod1 -i mod4 &
variety &
sleep 1
kitty --name dropdown --title dropdown tmux -f /etc/tmux/tmux.conf -2 new -s "dropdown" &
