#!/bin/bash

# You can call this script like this:
# $./volume.sh up
# $./volume.sh down
# $./volume.sh mute

function get_volume {
    pactl get-sink-volume $(pactl info | grep -i Sink | cut -d ':' -f2) | cut -d\% -f1 | cut -d\/ -f2 | awk '{print $1}' | egrep -x -E '[[:digit:]]+'
}

function is_mute {
    amixer get Master | grep '%' | grep -oE '[^ ]+$' | grep off > /dev/null
}

function send_notification {
    volume=`get_volume`
    # Make the bar with the special character ─ (it's not dash -)
    # https://en.wikipedia.org/wiki/Box-drawing_character
    bar=$(seq -s "─" $(($volume / 5)) | sed 's/[0-9]//g')
    # Send the notification
#    notify-send -i audio-volume-medium -t 150 -u normal "    $bar"
    notify-send " " -i audio-volume-medium -h int:value:$volume -h string:x-canonical-private-synchronous:volume &
}

case $1 in
    up)
	volume=`get_volume`
	if [ $volume -lt 100 ]
	then
	    pactl set-sink-volume $(pactl info | grep -i Sink | cut -d ':' -f2) +5%
	    send_notification
	fi
	;;
    down)
	volume=`get_volume`
	if [ $volume -gt 0 ]
	then
	    pactl set-sink-volume $(pactl info | grep -i Sink | cut -d ':' -f2) -5%
	    send_notification
	fi
	;;
    mute)
    	# Toggle mute
	pactl set-sink-mute $(pactl info | grep -i Sink | cut -d ':' -f2) toggle
	;;
esac
